let worksInfo = [
    {
        "title": "Octo hugs", 
        "keywords":["toy", "hardware", "research"], 
        "mainImage":"images/works/octo.jpg",
        "images":["images/works/octo-legs-rui.jpg", "images/works/octo.jpg", "images/works/octo-ash.jpg", "images/works/octo-toy1.jpg", "images/works/octo-toy2.jpg", "images/works/octo-prototype.png", "images/works/octo-maddy.jpg"],
        "subtitle": "a huggable plush toy", 
        "role": "Lead Designer", 
        "team": null, 
        "skills":["Interaction Design", "User Research", "User Testing", "Prototyping", "UX/UI", "Fabrication"],
        "tools":["Embedded Controller (Arduino)", "C/C++", "Adobe Illustrator", "Figma", "Fabrication"],
        "timeline": "7 months", 
        "shortDesc": "Octo hugs is a customizable, huggable plush toy created for children ages 5-8 years old with developmental disabilities to support them in times when they need a soothing hug, something soft to touch, or relaxing sounds to hear. When Octo hugs is hugged the toy will play ocean sounds, light up, and vibrate lightly to soothe the child. The toy is accompanied by an online site for parents to customize Octo hugs with their child.", 
        "featured":[{"place":"Instructables.com", "URL": "https://www.instructables.com/Octo-hugs-a-Huggable-Octopus-Plush-Toy/","date":"December 2019"}, {"place":"HINDSIGHT Exhibition", "URL":null, "date": "May 2020"}, {"place":"HINDSIGHT Publication", "URL":null, "date": "May 2020"}]
    },
    {
        "title": "Project Clueless", 
        "keywords":["hardware", "research", "IoT"], 
        "mainImage":"images/works/clueless.jpg",
        "images":["images/works/clueless-hangerprototype.jpg", "images/works/clueless-forcesensor.jpg", "images/works/clueless-present.jpg", "images/works/clueless.jpg"],
        "subtitle": "an IoT smart closet", 
        "role": "Lead Designer", 
        "team": null, 
        "skills":["Interaction Design", "User Research", "User Testing", "Prototyping"],
        "tools":["Embedded Controller (Arduino)", "C/C++", "NFC", "Real-time database", "Fabrication"],
        "timeline": "10 weeks", 
        "shortDesc": "Project Clueless is an IoT smart closet that knows three things: <ol><li><p>The items in the closet</p></li><li><p>Which items are on which hangers</p></li><li><p>The history of each item</p></li></ol>Project Clueless was created to help ease the process of selecting an outfit each day.", 
        "featured":null
    },
    {
        "title": "Cheddar the Cat", 
        "keywords":["toy", "web"], 
        "mainImage":"images/works/cheddarthecat.png",
        "images":null,
        "subtitle": "a virtual pet chrome extension", 
        "role": "Lead Programmer", 
        "team": null, 
        "skills":["Interaction Design", "UX/UI", "Prototyping", "Documentation"],
        "tools":["HTML/CSS", "JavaScript", "p5.js"],
        "timeline": "1 week", 
        "shortDesc": "Cheddar the Cat is a virtual pet chrome extension, featuring art by Mai Narushima. Cheddar will ask for pets and water throughout the day. They will also watch videos alongside you and will most often sleep in the corner of the screen. Cheddar will sometimes be annoying, sometimes be silent, but will always be a cute companion to have as you work.", 
        "featured":null
    },
    {
        "title": "File Management in Webstrates", 
        "keywords":["research", "web"], 
        "mainImage":"images/works/webstrates.jpg",
        "images":null,
        "subtitle": "research on managing files in a web-based collaborative software", 
        "role": "Assistant Researcher, Prototyper", 
        "team": ["Rebecca Ruvalcaba", "James Eagan, PhD"], 
        "skills":["Interaction Design", "UX/UI", "Prototyping", "Documentation"],
        "tools":["HTML/CSS", "JavaScript", "p5.js"],
        "timeline": "6 weeks", 
        "shortDesc": "Webstrates is a web-based collaborative software made up of web substrates. I conducted research on file management systems to design and prototype a web-based file management system on Webstrates.", 
        "featured":null
    },
    {
        "title": "Judge the Fly", 
        "keywords":["game", "alternative controller"], 
        "mainImage":"images/works/judge.jpg",
        "images": ["images/works/judge-gavel.jpg", "images/works/judge-wood.jpg", "images/works/judge-prototype.jpg", "images/works/judge.jpg","images/works/judge-game1.jpg", "images/works/judge-game2.jpeg"],
        "subtitle": "an alternative game controller", 
        "role": "Game Controller Designer",  
        "team": ["Rebecca Ruvalcaba", "Mickell Ford II", "Tiga Wu"], 
        "skills":["Interaction Design", "Prototyping"],
        "tools":["Embedded Controller (Arduino)", "C/C++", "Fabrication"],
        "timeline": "2 weeks", 
        "shortDesc": "Judge the Fly is a game where the player acts as judge in court - wearing a robe and handling a gavel. A fly is being distracting as the court session continues. The player's gavel strikes not only increase points, but they also determine the defendant's fate.", 
        "featured":null
    }, 
    {
        "title": "Controlling locomotion of robots", 
        "keywords":["research", "IoT"], 
        "mainImage":"images/works/robot.jpg",
        "images":null,
        "subtitle": "research on controlling robots via radio beacons", 
        "role": "Fabricator, Firmware Programmer", 
        "team": ["Rebecca Ruvalcaba", "Nour Boulahcen", "Mai-An Nguyen"], 
        "skills":["Prototyping", "Networking", "Gestural Interface"],
        "tools":["Embedded Controller (Arduino)", "C/C++", "Fabrication"],
        "timeline": "5 weeks", 
        "shortDesc": "This research project had the goal of controlling the locomotion of ground robot units in a physical space via radio beacons. The advantage of radio beacons is the radio signal can reach farther distances and the beacons do not need to be contrained to a specific set up. We accomplished moving the locomotion of robots with radio beacons via a gestural interface.", 
        "featured":null
    },
    {
        "title": "Trauma in Drama", 
        "keywords":["game", "tablet"], 
        "mainImage":"images/works/trauma.jpg",
        "images":["images/works/tid-crew.jpg", "images/works/tid-music.jpg", "images/works/tid-signup.jpg", "images/works/tid-test.jpg", "images/works/tid-vn.jpeg", "images/works/trauma.jpg"],
        "subtitle": "a visual novel with interactive mini games", 
        "role": "Lead Programmer, Scriptwriter", 
        "team": ["Rebecca Ruvalcaba", "Catherine Pavell", "Madeleine Guinness"], 
        "skills":["User Testing", "Narrative Design", "UX/UI", "Documentation"],
        "tools":["Unity", "C#", "Twine"],
        "timeline": "3 weeks", 
        "shortDesc": "Trauma in Drama is a visual novel with additional interactive mini games. The story follows Chloe, a high school student interested in the school musical. With the help of her friends and some practice, Chloe has a real shot at getting the lead role! Make friends, put your musical skills to the test, and see how you measure up to your rivals! Try not to get too traumatized in this high stakes high school drama story.", 
        "featured":null
    },
    {
        "title": "Mosquito Bonito", 
        "keywords":["game", "VR", "mobile"], 
        "mainImage":"images/works/mosquito.jpg",
        "images": ["images/works/mosquito-tongue.jpg", "images/works/mosquito-target.jpg", "images/works/mosquito-eat.jpg", "images/works/mosquito.jpg"],
        "subtitle": "a VR mobile game with Google Cardboard", 
        "role": "Lead Programmer", 
        "team": ["Rebecca Ruvalcaba", "Chella Man", "Tiga Wu"], 
        "skills":["Interaction Design", "VR", "User Testing","Documentation"],
        "tools":["Unity", "C#", "Google Cardboard"],
        "timeline": "2 weeks", 
        "shortDesc": "Mosquito Bonito is a casual bug eating game where players play as a froggy, enjoying a chill summer day and catching bugs. This VR game runs on mobile and can be played with a Google Cardboard.", 
        "featured":null
    },
    {
        "title": "Clearing House", 
        "keywords":["game", "tabletop"], 
        "mainImage":"images/works/clearinghouse.jpg",
        "images": ["images/works/clearing-board.jpg", "images/works/clearing-move.jpg", "images/works/clearing-doublemove.jpg", "images/works/clearing-attack.jpg", "images/works/clearing-rattack.jpg", "images/works/clearing-abduct.jpg", "images/works/clearinghouse.jpg"],
        "subtitle": "a strategy turn-based board game", 
        "role": "Project Manager, Fabricator", 
        "team": ["Rebecca Ruvalcaba", "Lionel Miele-Herndon", "Madeleine Guinness", "Mickell Ford II"], 
        "skills":["Prototyping", "Documentation", "Game Design"],
        "tools":["Adobe Illustrator", "Fabrication"],
        "timeline": "2 weeks", 
        "shortDesc": "Clearing House is a turn-based mafia board game. The goal of the game is to be the last player standing by any means necessary. The player can move around the board, attack, defend with armor, abduct, ambush, or intervene an attack during a turn.", 
        "featured":null
    },
    {
        "title": "BFFs", 
        "keywords":["game", "web"], 
        "mainImage":"images/works/bffs.png",
        "images":["images/works/bff-bee.png", "images/works/bff-wasp.png", "images/works/bff-powerup.png", "images/works/bffs.png"],
        "subtitle": "a shoot 'em up game", 
        "role": "Game Designer and Developer", 
        "team": null, 
        "skills":["User Testing", "Documentation", "Game Design"],
        "tools":["Unity", "C#", "Adobe Photoshop"],
        "timeline": "2 weeks", 
        "shortDesc": "BFF is a shoot 'em up (SHMUP) game where the player plays as a bee trying to protect their human friend from the wasp kingdom.", 
        "featured":null
    }, 
    {
        "title": "Camazotz", 
        "keywords":["game", "web"], 
        "mainImage":"images/works/camazotz.png",
        "images": ["images/works/camazotz-level1.jpg", "images/works/camazotz-level2.jpg", "images/works/camazotz.png"],
        "subtitle": "a mayan-inspired platformer", 
        "role": "Game Designer and Developer", 
        "team": null, 
        "skills":["User Testing", "Documentation", "Game Design"],
        "tools":["Unity", "C#", "Adobe Illustrator"],
        "timeline": "2 weeks", 
        "shortDesc": "Camazotz is a platformer game where Camazotz, a Mayan bat god, ventures from Xibalba to Earth's surface to play ball with the help of his owl messenger god friends. The game plays off of the pictorgraph mechanic - when on a wall Camazotz is a pictograph to hide from the mayan people, but in the land of the living Camazotz can move around and jump as they please.", 
        "featured":null
    },
    {
        "title": "Wolfman Mayhem", 
        "keywords":["game", "PC", "multiplayer"], 
        "mainImage":"images/works/wolfman.png",
        "images":null,
        "subtitle": "an asymmetrical multiplayer game", 
        "role": "Game Designer", 
        "team": ["Rebecca Ruvalcaba", "Munro Hoberman", "Ian Henderson"], 
        "skills":["User Testing", "UX/UI", "Asymetrical Design", "Prototyping"],
        "tools":["Unity", "C#", "Adobe Illustrator"],
        "timeline": "2 weeks", 
        "shortDesc": "Wolfman Mayhem is an asymmetrical multiplayer game - one player plays as the wolfman and two players play as puppies. The wolfman play in a 3D Doom-like contruction of the manor while the puppies play in a 2D contruction of the manor, only able to see a particular radius around themselves.", 
        "featured":null
    },
    {
        "title": "Zelda-inspired Ring Box and Rupees", 
        "keywords":["toy", "collectible"], 
        "mainImage":"images/works/zeldaringbox.jpg",
        "images":["images/works/zelda-top.jpg", "images/works/zelda-open.jpg", "images/works/zelda-rupees.jpg", "images/works/zelda-rupeeshappy.jpg", "images/works/zeldaringbox.jpg"],
        "subtitle": "a set of one-of-a-kind collector toys", 
        "role": "Designer", 
        "team": ["Rebecca Ruvalcaba", "Mickael Bouhier"], 
        "skills":["3D Modeling", "Prototyping"],
        "tools":["AutoCAD", "Fabrication"],
        "timeline": "4 days", 
        "shortDesc": "This zelda-inspired ring nox and rupees set was created for my proposal to my fiancée - the ultimate zelda fan. The ring box and rupees were 3D printed and painted. Mickael Bouhier aided with the 3D modeling process.", 
        "featured":null
    }
    ];

    // {
    //     "title": "Input Physicalization", 
    //     "keywords":["research", "data visualization"], 
    //     "mainImage":"images/works/input.jpg",
    //     "images":null,
    //     "subtitle": "research on input data physicalization", 
    //     "role": "Lead Researcher", 
    //     "team": ["Rebecca Ruvalcaba", "Nathalie Bressa, PhD", "Samuel Huron, PhD"], 
    //     "skills":["Research", "Prototyping", "Documentation", "User Testing"],
    //     "tools":["InDesign", "Fabrication"],
    //     "timeline": "In progress", 
    //     "shortDesc": "Input Physicalization is the intersection between input data visualization and data physicalization. No one has specifically explored systematically the design patterns and techniques of input physicalization, which can be useful for gathering data in an engaging way from the public.", 
    //     "featured":null
    // },
    // {
    //     "title": "Farmer Round Up", 
    //     "keywords":["toy", "research", "tangible tokens"], 
    //     "mainImage":"images/works/farmer.jpg",
    //     "images":null,
    //     "subtitle": "a hybrid board game to improve dexterity in elders", 
    //     "role": "Lead Designer", 
    //     "team": ["Rebecca Ruvalcaba","Neila Rostom"], 
    //     "skills":["Interaction Design", "Research", "Prototyping"],
    //     "tools":["Unity", "C#", "Adobe Illustrator", "Fabrication"],
    //     "timeline": "In progress", 
    //     "shortDesc": "", 
    //     "featured":null
    // },